import { Copy, Check } from "lucide-react";
import { useState } from "react";

// generated by gemini T_T

export const EmailComponent = () => {
    const email = "marvin.masubay.042005@gmail.com";
    const [copied, setCopied] = useState(false);

    const handleCopy = async (e) => {
        e.preventDefault();
        e.stopPropagation();

        // Method 1: The Modern Way (HTTPS / Localhost)
        if (navigator.clipboard && window.isSecureContext) {
            try {
                await navigator.clipboard.writeText(email);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
                return;
            } catch (err) {
                console.error('Modern copy failed', err);
            }
        }

        // Method 2: The "Old School" Fallback (Works on HTTP/Local Network)
        // We create an invisible text box, select it, and run the copy command
        const textArea = document.createElement("textarea");
        textArea.value = email;
        
        // Move it off-screen so the user doesn't see it
        textArea.style.position = "absolute";
        textArea.style.left = "-9999px";
        
        document.body.appendChild(textArea);
        textArea.select();
        
        try {
            document.execCommand('copy'); // The magic command
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Fallback copy failed', err);
        }
        
        document.body.removeChild(textArea);
    };

    return (
        // Added 'relative z-10' to ensure it sits on top of any background layers
        <div className="flex flex-row items-center gap-1 text-sm font-public relative z-10">
            
            <a 
                href={`mailto:${email}`} 
                className="underline hover:text-teal-main transition-colors"
            >
                {email}
            </a>

            <button 
                // CRITICAL FIX: explicit type prevents form submission
                type="button" 
                onClick={handleCopy}
                className="p-1 hover:bg-black/10 rounded-md transition-all cursor-pointer flex items-center justify-center"
                aria-label="Copy email address"
            >
                {/* Using a transition helps you see the change. 
                   If 'copied' is true, show Check. Else show Copy.
                */}
                <div className={`transition-all duration-300 ${copied ? 'scale-100' : 'scale-0 hidden'}`}>
                    <Check size="16" className="text-green-600" />
                </div>
                <div className={`transition-all duration-300 ${copied ? 'scale-0 hidden' : 'scale-100'}`}>
                    <Copy size="16" />
                </div>
            </button>
        </div>
    );
};